version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./web:/var/www/html
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:7.1-fpm
        volumes:
            - ./web:/var/www/html
        networks:
            - code-network

networks:
    code-network:
        driver: bridge